/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#c3f5ff",
        "surface": "#0d1322",
        "surface-container-highest": "#2f3445",
        "on-tertiary-fixed-variant": "#004395",
        "secondary": "#7bd0ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-background": "#dde2f8",
        "tertiary-fixed": "#d8e2ff",
        "on-tertiary": "#002e6a",
        "on-error": "#690005",
        "tertiary-container": "#bdd0ff",
        "surface-variant": "#2f3445",
        "on-primary": "#00363d",
        "on-primary-fixed-variant": "#004f58",
        "on-surface": "#dde2f8",
        "on-primary-fixed": "#001f24",
        "surface-bright": "#33394a",
        "on-primary-container": "#00626e",
        "on-tertiary-container": "#0055b8",
        "surface-container": "#191f2f",
        "on-surface-variant": "#bac9cc",
        "inverse-on-surface": "#2a3040",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#9cf0ff",
        "on-secondary": "#00354a",
        "surface-dim": "#0d1322",
        "surface-container-low": "#151b2b",
        "background": "#0d1322",
        "on-secondary-fixed-variant": "#004c69",
        "on-secondary-container": "#00374d",
        "surface-container-lowest": "#080e1d",
        "error-container": "#93000a",
        "secondary-fixed": "#c4e7ff",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#00daf3",
        "inverse-primary": "#006875",
        "primary-container": "#00e5ff",
        "on-secondary-fixed": "#001e2c",
        "surface-tint": "#00daf3",
        "surface-container-high": "#242a3a",
        "secondary-container": "#00a6e0",
        "on-tertiary-fixed": "#001a42",
        "tertiary": "#e7ecff",
        "tertiary-fixed-dim": "#adc6ff",
        "outline": "#849396",
        "outline-variant": "#3b494c",
        "inverse-surface": "#dde2f8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "space-3xl": "3rem",
        "panel-padding-compact": "0.75rem",
        "space-2xl": "2rem",
        "space-xs": "0.25rem",
        "space-2xs": "0.125rem",
        "gutter-desktop": "1rem",
        "space-xl": "1.5rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "panel-padding-standard": "1.25rem",
        "space-lg": "1rem",
        "gutter-mobile": "0.75rem"
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-code-lg": ["JetBrains Mono", "monospace"],
        "label-code-md": ["JetBrains Mono", "monospace"],
        "label-code-sm": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
